[project]
name = "udemy-python"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "flask>=3.1.1",
]

[tool.uv.workspace]
members = [
    "Projects/Data handling projects",
]
